### ISSUE TITLE
User inputs validation

### ISSUE THREAD

**Issue by vincentClaeysen** [mlecoutre/nounou#20] opened 2012-11-14 07:09 UTC
In the "best practices"/"guidelines" topic, why not using a javascript validation library (as javax.validation for the server side)
See: http://www.webreference.com/programming/javascript/jquery/form_validation/index.html
concerning jquery.validation - it's very sexy

**Comment by mlecoutre** [comment] 2012-11-14 08:48
Duplicate of Issue #4

**Closed as completed by mlecoutre** 2012-11-14 08:48 UTC
Labels: duplicate, enhancement
